### ISSUE TITLE
Doesn't work with Sirius 6.2.0 and higher

### ISSUE THREAD

**Issue by echebbi** [gemoc/ale-lang#87]
## Description

As of Sirius 6.2.0, the interface `IInterpreterWithDiagnostic` does not exist anymore (see [release notes](https://www.eclipse.org/sirius/doc/Release_Notes.html#sirius6.2.0)). However, as ALE seems to require it, using a version of Sirius >= 6.2.0 makes it unusable:

 - ALE scripts are not validated anymore (e.g. the type checker is not called),
 - ALE scripts cannot be run anymore (the console prints `Run <script_name>` then nothing appears, and no error is shown).

The only visible clues are:

 - an error marker on the _.ale_ script: "Error executing EValidator"
 - an error message in the _Log View_ displaying the following stacktrace:

```
java.lang.NoClassDefFoundError: org/eclipse/sirius/common/tools/api/interpreter/IInterpreterWithDiagnostic$IEvaluationResult
	at org.eclipse.emf.ecoretools.validation.AleValidator.checkIsValid(AleValidator.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator$MethodWrapper.invoke(AbstractDeclarativeValidator.java:127)
	at org.eclipse.xtext.validation.AbstractDeclarativeValidator.internalValidate(AbstractDeclarativeValidator.java:318)
	at org.eclipse.xtext.validation.AbstractInjectableValidator.validate(AbstractInjectableValidator.java:71)
	at org.eclipse.xtext.validation.CompositeEValidator.validate(CompositeEValidator.java:150)
	...
Caused by: java.lang.ClassNotFoundException: org.eclipse.sirius.common.tools.api.interpreter.IInterpreterWithDiagnostic$IEvaluationResult cannot be found by org.eclipse.emf.ecoretools.ale_1.0.0.201911221554
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:514)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:425)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:417)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 40 more
```

## Possible Actions

I think that the culprit is the following import:
https://github.com/gemoc/ale-lang/blob/ffda463d1748e1b69dab2af688ca77c25055ce71/plugins/org.eclipse.emf.ecoretools.ale/src/org/eclipse/emf/ecoretools/ale/ALEInterpreter.java#L57

We should import `org.eclipse.sirius.common.tools.api.interpreter.IEvaluationResult` instead when Sirius >= 6.2.0 is installed but I admit that I don't really know how to handle properly different versions of a same plug-in.

Alternatively, we should at least specify version bounds for the Sirius plug-ins we depend on so that users know which versions they can use.
